import modules.errors.insert as insert
import modules.extract_name_from_email as extract
import modules.find_broken_links_from_input_file as check
import modules.find_broken_links_from_input_url as url_input
import modules.scrape_emails_and_social_media_with_new_links as scrape_n
import modules.scrape_emails_and_social_media as scrape


